version: '3.8'

services:
  app:
      image: malins062/fastapi-app:latest
      container_name: fastapi_web
      build:
        context: .api/app
        dockerfile: Dockerfile
      ports:
        - "8000:8000"
      depends_on:
        - mongo
      environment:
        - MONGO_URI=mongodb://db_mongo/
      command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
      networks:
        - netapi

  nginx:
      image: nginx:latest
      container_name: ngnix
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
      depends_on:
        - app
      networks:
        - netapi

  mongo:
      image: mongo:latest
      container_name: db_mongo
      ports:
        - "27017:27017"
      volumes:
        - mongodb_data:/data/db
      networks:
        - netapi

  redis_server:
      image: redis:latest
      container_name: db_redis
      restart: "always"
      volumes:
          - ./redisdata:/data
      deploy:
          resources:
              limits:
                  cpus: '0.50'
                  memory: 512M
              reservations:
                  cpus: '0.25'
                  memory: 256M
      ports:
          - "6379:6379"
      command: >
          sh -c '
            mkdir -p /usr/local/etc/redis &&
            echo "bind 0.0.0.0" > /usr/local/etc/redis/redis.conf &&
            echo "requirepass $REDIS_PASSWORD" >> /usr/local/etc/redis/redis.conf &&
            echo "appendonly yes" >> /usr/local/etc/redis/redis.conf &&
            echo "appendfsync everysec" >> /usr/local/etc/redis/redis.conf &&
            echo "user default on nopass ~* +@all" > /usr/local/etc/redis/users.acl &&
            echo "user $REDIS_USER on >$REDIS_USER_PASSWORD ~* +@all" >> /usr/local/etc/redis/users.acl &&
            redis-server /usr/local/etc/redis/redis.conf --aclfile /usr/local/etc/redis/users.acl
          '
      healthcheck:
          test: ["CMD", "redis-cli", "-a", "$REDIS_PASSWORD", "ping"]
          interval: 30s
          timeout: 10s
          retries: 5
      tty: true
      stdin_open: true
      networks:
        - netapi

  telegram-bot:
      image: malins062/fastapi-telegram-bot:latest
      container_name: fastapi_telegram_bot
      restart: "always"
      stop_signal: SIGINT
      env_file:
          -  ./cfg/evtc-telegram-bot/.env
      depends_on:
          - redis
      networks:
        - netapi

volumes:
  mongodb_data:

networks:
  netapi:
    driver: bridge
