version: '3.8'

services:
  app:
    build:
      context: .api/app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/messages
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile.telegram
    environment:
      - TELEGRAM_BOT_TOKEN=<your_telegram_bot_token>
      - MONGO_URI=mongodb://mongo:27017/messages
    depends_on:
      - redis

volumes:
  mongodb_data:
