name: Lint and check types

on:
  push:
    branches: [dev]
  pull_request:
    branches: [main, dev]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install poetry
      run: |
        pip install pipx
        pipx install poetry

    - name: Validate the structure of the pyproject.toml
      run: |
        poetry check

    - name: Verify that poetry.lock is consistent with pyproject.toml
      run: |
        poetry lock --check

    - name: Install dependencies
      run: |
        poetry install

    - name: Check code formatting by black
      run: |
        poetry run black . --check

    - name: Lint code by ruff
      run: |
        poetry run ruff check .

#    - name: Check types by pyright
#      run: |
#        poetry run pyright