name: Build and Publish Docker Images

on:
#  pull_request:
#    branches: [ main ]

  workflow_dispatch:

jobs:
  publish-bot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Publish to Registry Telegram-bot
      uses: docker/build-push-action@v2
      with:
        context: ./bot/
        push: true
        tags: malins062/fastapi-telegram-bot:latest

    - name: Publish to Registry FastAPI-app
      uses: docker/build-push-action@v2
      with:
        context: ./api/
        push: true
        tags: malins062/fastapi-app:latest
